apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: angular
  name: angular
  namespace: asg-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: angular
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: angular
    spec:
      containers:
      - command:
        - /bin/sh
        - /usr/src/app/angular/startup.sh
        image: angular
        name: angular
        ports:
        - containerPort: 4200
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/app/
          name: angular-claim0
      restartPolicy: Always
      volumes:
      - name: angular-claim0
        persistentVolumeClaim:
          claimName: angular-claim0
status: {}
