apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --provider=openshift
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: angular
  name: angular
spec:
  replicas: 1
  selector:
    io.kompose.service: angular
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: angular
    spec:
      containers:
      - command:
        - /bin/sh
        - /usr/src/app/angular/startup.sh
        image: ' '
        name: angular
        ports:
        - containerPort: 4200
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/app/
          name: angular-claim0
      restartPolicy: Always
      volumes:
      - name: angular-claim0
        persistentVolumeClaim:
          claimName: angular-claim0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - angular
      from:
        kind: ImageStreamTag
        name: angular:latest
    type: ImageChange
status: {}
