apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: django
  name: django
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: django
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
